spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT-ID}
            client-secret: ${CLIENT-SECRET}
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
